[connections.gsheets]
type = "service_account"
project_id = "kinetic-pilot-451813-u4"
private_key_id = "269f6fdeb553df75750d7525d0ed281e2c9d478c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCZYWUHLbXLV5lP
2zTvfkncpUZ1wINBdQJXyLsFzyAfCj9ncCxLsW6vZD8qzXdEGIvbx5rfD3xqDHjG
RYIS+387g5FUlTJ4pQYfQpv28+++tmPbADCzhYRPzisYdjGXCiEEN/mvOt6riRJH
gnBy16s+Qj4WjURLbMk6L6tEM6Gfs2VGG10lv7osEbibKs5+TGNU5rrFibz7muKc
r+uF5lw+e4UJmw2MBVMGsatsOENXeG6kIWemrtJus8PdpRpHd07WvCrj72HmOEk3
zR9+FTMsVuXe4HtClCFoZbEVtphxNLbq51XqORyYGfPnUiqsqnAHrQcUgYAKFUY+
g9PF3gjhAgMBAAECggEAE+nf+MZfwbqKEmLitMxn8RB5PS0FLZCwQO70Dy1E3ZrS
QA8BhUNQXE+u3tMFzs7EC8EW06qaS9d6L73TBT1nV7X9fqaPQrgkOxdGEhI6OH/M
J6EW8ZveYZEiKb8gsZw0TKyqy2wggFNfzu55xINJPaBSmNF3AjbpylbpjMWKUKZB
wZzdGcE1Qt+Vxrv4aCw8tXzWzH0zRS4EFKxCw8LurmTnqXB8tHWK5Bktt4Ev5toU
TadnA5SqA1FVSW8l4lY2sMRbI0L2le/3I71BhmcVhB9viCmYSipk5wwpNfYgvfXr
1Tv5Ya7AWTvDLFSWHO8ptHIC5ZemMDeVK9luEIk4RQKBgQDLNSnKv0Ld4FYGtDc0
imaUu+G+1jcsUWMDyBCs+uRBuNcEt/sqtxsCXobabD/i+FNOMEHzT/rAcADmpHiP
f2h+XwC4jMEXDGHS57bcXk6q1THzhUrql6zlLAVY1ZKS2sI0/lOmt5tkRTlJTxqV
59sTyTY7NcBEHPFPASwXSe0wbQKBgQDBOljJCq0t43E9rsmQ6EmT95KrL/immgm9
XlViJmCdduewzPm2h9sabc/ijrY555if9eD0J6hTfoEFvfanopMPOqW4Kw5BMjNl
yBVSUhWtku9+OE33wHKDEbQ547BwD8/hVPIjU9udaWL5fn4i1mMqGe6siCBaKPHU
Zrs+Nh25xQKBgQCHFuChmGSre+e0rTnGA/wOBJkedOpY3AInEWmElYYI6wiGaoje
7LtX599edXhDOzKmWA5/4jugktUGf3BmdRzSZfXkui3jVKfzvXcjKM7DYtfCPGqB
ajPWZl1noRO/7Q4OjMSvoH/9OMfMpHnYDjrl/G3BDwqyPUtuaikVkl/MQQKBgEtG
aq4vTZXx4/yuqfGcvIU7TlUIRCrLGX4/UK4C22Kcntf+kk1skYuzOeg9xnm6Ynf2
dqNHC8kzIBpXjc5yhC3LoCGmDFCTuPguwTenqLBM7KXUU3Nv8mxjKj3fGK4fStGy
oP3oPkcNdjRR9dumf004ewWVplzZVJR1TP6IYH4tAoGBAIMQ5Ol0yS4K+6wqwzL/
AitlXt3hL0gb9SrWQiE3tcw9YODjZTQg1eM4FgbEFa3f4HJvOYp9xdwgUW6c+PMK
bK49TwRERmtimHIP0AVtkeciGNct523MZxxwAnH4MyWd7ZaKebt/MYqp2u5OFFoK
k1zNE+S2PDfNCps8LHvOd/CO
-----END PRIVATE KEY-----
"""
client_email = "canhnho@kinetic-pilot-451813-u4.iam.gserviceaccount.com"
client_id = "107200754954040666441"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/canhnho%40kinetic-pilot-451813-u4.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
